name: Crawl GW2 Wiki Events & Loot

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 rapidfuzz

      - name: Crawl Guild Wars 2 Wiki loot
        run: python py/wiki_loot_crawler.py

      - name: Commit updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main || true
          git add data/maps/*.json data/manifest.json
          git commit -m "Auto-update GW2 Wiki loot [skip ci]" || echo "No changes to commit"
          git push
