name: Crawl GW2 Wiki Loot

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests beautifulsoup4 rapidfuzz
      - name: Run crawler
        run: python py/wiki_loot_crawler.py
      - name: Git Sync
        run: |
          git config pull.rebase false
          git pull origin main || echo "No remote changes"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/maps/*.json data/manifest.json
          git commit -m "Wiki loot dump per map (auto-crawl) [skip ci]" || echo "No changes"
          git push
