name: GW2 Crawl

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1'  # Elke maandag

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run GW2 Master Crawler
        run: python py/gw2_master_crawler.py
