name: Refresh GW2 Data

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: pip install requests

      - name: Refresh items.csv
        run: python py/refreshitems.py

      - name: Refresh achievements.csv
        run: python py/refreshachievements.py

      - name: Refresh maps.csv
        run: python py/refreshmaps.py

      - name: Refresh prices.csv
        run: python py/refreshprices.py

      - name: Pull remote changes
        run: |
          git config pull.rebase false
          git pull origin main || echo "Geen remote changes, safe to continue"

      - name: Commit en push alle CSV’s
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv
          git commit -m "Auto-update alle GW2 data-dumps [skip ci]" || echo "Geen wijzigingen"
          git push
